# Pytorch 

1. [Pytorch Basics](#1)
2. [Basic Math Operations](#2)

<a id = "1"></a>
## Pytorch Basics

In [1]:
import numpy as np
import torch

In [3]:
first_list = [[1,2,3], [4,5,6]]
first_array = np.array(first_list) 
print("Array type: {}".format(type(first_array)))
print("Array type: {}".format(np.shape(first_array)))
print("This is the array: {}".format(first_array))

Array type: <class 'numpy.ndarray'>
Array type: (2, 3)
This is the array: [[1 2 3]
 [4 5 6]]


In [4]:
first_tensor = torch.Tensor(first_list)
print("Array type: {}".format(first_tensor.type))
print("Array shape: {}".format(first_tensor.shape))
print("This is the tensor: {}".format(first_tensor))

Array type: <built-in method type of Tensor object at 0x000001A9310E0720>
Array shape: torch.Size([2, 3])
This is the tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
# numpy ones 
a = np.ones((2,3))
print("a:",a)
# torch ones
b = torch.ones((2,3))
print("b:",b)


a: [[1. 1. 1.]
 [1. 1. 1.]]
b: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
# numpy zeros
c = np.zeros((2,2))
print("c:", c)
# torch zeros
d = torch.zeros((2,2))
print("d:", d)

c: [[0. 0.]
 [0. 0.]]
d: tensor([[0., 0.],
        [0., 0.]])


In [15]:
# numpy random 
print("Numpy: {}".format(np.random.rand(2,3)))
print("Torch: {}".format(torch.rand(2,3)))

Numpy: [[0.52469322 0.05462182 0.71000069]
 [0.27453357 0.92613739 0.33390924]]
Torch: tensor([[0.6482, 0.6075, 0.4100],
        [0.1995, 0.3647, 0.3322]])


In [19]:
# creating an array
array = np.random.rand(2,2)
print("Array: {}".format(array))
print("Array: {}".format(type(array)))

# numpy to tensor
numpy2Tensor = torch.from_numpy(array)
print("Numpy2Tensor: {}".format(numpy2Tensor))
print("Numpy2Tensor: {}".format(numpy2Tensor))

# tensor to numpy
tensor2Numpy = numpy2Tensor.numpy()
print("Back2Numpy: {}".format(tensor2Numpy))
print("Back2Numpy: {}".format(type(tensor2Numpy)))

Array: [[0.16063571 0.89746205]
 [0.67314278 0.99674099]]
Array: <class 'numpy.ndarray'>
Numpy2Tensor: tensor([[0.1606, 0.8975],
        [0.6731, 0.9967]], dtype=torch.float64)
Numpy2Tensor: tensor([[0.1606, 0.8975],
        [0.6731, 0.9967]], dtype=torch.float64)
Back2Numpy: [[0.16063571 0.89746205]
 [0.67314278 0.99674099]]
Back2Numpy: <class 'numpy.ndarray'>


<a id = "2"></a>
## Basic Math Operations

In [20]:
# create tensor 
tensor = torch.ones(3,3)
print("\n",tensor)

# Resize
print("{}{}\n".format(tensor.view(9).shape,tensor.view(9)))

# Addition
print("Addition: {}\n".format(torch.add(tensor,tensor)))

# Subtraction
print("Subtraction: {}\n".format(tensor.sub(tensor)))

# Element wise multiplication
print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor)))

# Element wise division
print("Element wise division: {}\n".format(torch.div(tensor,tensor)))

# Mean
tensor = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor.mean()))

# Standart deviation (std)
print("std: {}".format(tensor.std()))


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

Subtraction: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Element wise multiplication: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Element wise division: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Mean: 3.0
std: 1.5811388492584229


In [21]:
# Variables 

from torch.autograd import Variable

var = Variable(torch.ones(3), requires_grad = True)
var

tensor([1., 1., 1.], requires_grad=True)

In [23]:
array = [2,4]
tensor = torch.Tensor(array)
x = Variable(tensor, requires_grad = True)
y = x**2
print("y = ", y)

o = (1/2)*sum(y)
print("o =", o)

o.backward()

print("gradients: {}".format(x.grad))

y =  tensor([ 4., 16.], grad_fn=<PowBackward0>)
o = tensor(10., grad_fn=<MulBackward0>)
gradients: tensor([2., 4.])
